### PR TITLE
feat: add a blog page

### PR DESCRIPTION
**Pull request by Kawaki-1998**
Hello team  I have added New Blog page to the code

- Created two blog post with Lorem ipsum text
- Added read more and read less button based on the size of the blog 

Any changes/Feedbacks are much appreciated 

image

### CODE REVIEW

**Comment by jadeleafmoon** [comment]
@Kawaki-1998 Great work!

## Highlights
- Great code style, variable names and syntax. 
- Good code logic

## Suggestions
Can you make these two updates?

1. Put a screenshot of the new blog page in your original PR comment. This will help your teammates see the change right away :)

2. Put a hyperlink in the title of the blog post. 
For example, "[Sample Blog Post](#)" where it points to an empty site like "#".

**Comment by Kawaki-1998** [comment]
@jadeleafmoon I have updated the blog page

**Comment by jadeleafmoon** [comment]
@Kawaki-1998 Looks great! I'll merge it to main.

**Comment by jadeleafmoon** [comment]
Okay, it's working! Merging.

**Pull request merged**
